name: My Pterodactyl Restarter
on: [ push ]
jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: restart
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: 'https://panel.sillydev.co.uk'
          server-id: ${{ secrets.PTE_PANEL_ID}}
          bearer-token: ${{ secrets.PTE_BEARER_TOKEN  }}
          power-action: 'restart'
